### ISSUE TITLE
What is the difference between redlock and simple-redlock

### ISSUE THREAD

**Issue by Diluka** [anchan828/nest-redlock#522]
which one is recommended to use?

**Comment by anchan828** [comment]
Hi @Diluka, Looks like I forgot to update README...
Basically, I recommend using @anchan828/nest-redlock. The main logic is to use node-redlock because you can expect extensive documentation, number of users, and bug fixes.

The simple-redlock was first made for convenience in my project's specification. This will be removed as it will only cause confusion.

**Comment by anchan828** [comment]
Removed simple-redlock from repo. If you use it, please use @anchan828/nest-redlock.😀
